[package]
name = "flow-parser"
version = "0.1.0"
edition = "2021"
authors = ["Matt Barkway <contact@mattbarkway.dev>"]
license = "MIT"
repository = "https://github.com/MattBarkway/flow-parser"


[dependencies]
serde_json = "1.0.145"
serde = { version = "1.0.227", features = ["derive"] }
